server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务

  cloud:
    config:
      server:
        git:
          uri: https://github.com/xcdh127/springcloud-config.git  #github上面的仓库地址
          #### 搜索目录
          search-paths:
            - springcloud-config
          skip-ssl-validation: true

        ### 读取分支
      label: master


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka







